### ISSUE TITLE
Signup issue

### ISSUE THREAD

**Issue by Leywiggle** [jebkor/battletrackr#8]
**Describe the bug**
When signing up, there is no indication if the process went good or bad. Console shows an 500 Server error, which indicates it went bad.

An email to confirm my account did appear in my Spam inbox.

**To Reproduce**
1. Go to signup.
2. Fill out information.
3. Click "Sign-up".
4. See error in Console.

**Expected behavior**
A confirmation telling me that the account was created (or a message, why it wasn't).

**Desktop (please complete the following information):**
 - OS: Windows 10.
 - Browser: Chrome.
 - Version: 75.0.3770.80 (Official Build) (64-bit).

**Comment by jebkor** [comment]
Should be fixed with pull request #9
